[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["glibc", "musl", "jemalloc"]

[deploy]
startCommand = "npm run start"
# healthcheckPath = "/"
# healthcheckTimeout = 500
restartPolicyType = "never"
