import React from 'react'
import { Sparkles } from 'lucide-react'
import Markdown from 'react-markdown'
import { useTranslation } from '@/i18n/client'
import { MarkdownComponents } from '../RichTextEditor/markdown-components'
import { LoadingState } from './loading-state'

interface RecommendationContentProps {
  recommendationData: string[]
  isLoading: boolean
}

export function RecommendationContent({ recommendationData, isLoading }: RecommendationContentProps) {
  const { t } = useTranslation()
  
  return (
    <div className='space-y-6'>
      {isLoading && <LoadingState isOverlay />}
      <div className='bg-gradient-to-r from-blue-300 to-blue-500 dark:from-blue-400 dark:to-blue-600 p-6 rounded-lg'>
        <h3 className='text-xl font-medium text-white mb-3 flex items-center'>
          <Sparkles className='w-5 h-5 mr-2' />
          {t('app.home.personalizedRecommendations') || 'Your Personalized Recommendations'}
        </h3>
        <div className='prose dark:prose-invert prose-sm max-w-none'>
          <Markdown components={MarkdownComponents}>{recommendationData.join('\n')}</Markdown>
        </div>
      </div>
      <div className='text-sm text-gray-500 dark:text-gray-400 italic'>
        {t('app.home.aiDisclaimer') || 'Recommendations are generated by AI based on your reading history and may not be perfect.'}
      </div>
    </div>
  )
}