import { Sparkles } from 'lucide-react'

// import { Streamdown } from 'streamdown'
import { useTranslation } from '@/i18n/client'

// import { MarkdownComponents } from '../RichTextEditor/markdown-components'
import { PulseLoader } from './pulse-loader'

interface RecommendationContentProps {
  recommendationData: string[]
  isLoading: boolean
}

export function RecommendationContent({
  recommendationData,
  isLoading,
}: RecommendationContentProps) {
  const { t } = useTranslation()

  return (
    <div className="space-y-6">
      <div className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm transition-shadow duration-200 hover:shadow-md dark:border-zinc-700 dark:bg-zinc-800">
        <div className="relative border-b border-gray-100 bg-gradient-to-br from-slate-50 to-blue-50/50 p-6 dark:border-zinc-700 dark:from-slate-800 dark:to-blue-900/20">
          {isLoading && <PulseLoader />}
          <h3 className="mb-1 flex items-center text-xl font-semibold text-gray-900 dark:text-zinc-50">
            <Sparkles className="mr-2 h-5 w-5 text-blue-500 dark:text-blue-400" />
            {t('app.home.personalizedRecommendations') ||
              'Your Personalized Recommendations'}
          </h3>
          <p className="text-sm text-gray-600 dark:text-zinc-400">
            AI-powered suggestions based on your reading preferences
          </p>
        </div>
        <div className="p-6">
          <div className="prose dark:prose-invert prose-sm max-w-none text-gray-900 dark:text-zinc-50">
            {/* <Streamdown components={MarkdownComponents}> */}
            {recommendationData.join('')}
            {/* </Streamdown> */}
          </div>
        </div>
      </div>
      <div className="flex items-center gap-2 rounded-lg border border-gray-200 bg-gray-50 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-900">
        <div className="h-2 w-2 rounded-full bg-blue-400 opacity-60"></div>
        <p className="text-sm text-gray-600 dark:text-zinc-400">
          {t('app.home.aiDisclaimer') ||
            'Recommendations are generated by AI based on your reading history and may not be perfect.'}
        </p>
      </div>
    </div>
  )
}
