import { Sparkles } from 'lucide-react'
import { Streamdown } from 'streamdown'
import { useTranslation } from '@/i18n/client'
import { MarkdownComponents } from '../RichTextEditor/markdown-components'
import { PulseLoader } from './pulse-loader'

interface RecommendationContentProps {
  recommendationData: string[]
  isLoading: boolean
}

export function RecommendationContent({
  recommendationData,
  isLoading,
}: RecommendationContentProps) {
  const { t } = useTranslation()

  return (
    <div className='space-y-6'>
      <div className='bg-white dark:bg-zinc-800 border border-gray-200 dark:border-zinc-700 rounded-xl shadow-sm hover:shadow-md transition-shadow duration-200 overflow-hidden'>
        <div className='bg-gradient-to-br from-slate-50 to-blue-50/50 dark:from-slate-800 dark:to-blue-900/20 p-6 relative border-b border-gray-100 dark:border-zinc-700'>
          {isLoading && <PulseLoader />}
          <h3 className='text-xl font-semibold text-gray-900 dark:text-zinc-50 mb-1 flex items-center'>
            <Sparkles className='w-5 h-5 mr-2 text-blue-500 dark:text-blue-400' />
            {t('app.home.personalizedRecommendations') ||
              'Your Personalized Recommendations'}
          </h3>
          <p className='text-gray-600 dark:text-zinc-400 text-sm'>
            AI-powered suggestions based on your reading preferences
          </p>
        </div>
        <div className='p-6'>
          <div className='prose dark:prose-invert prose-sm max-w-none text-gray-900 dark:text-zinc-50'>
            <Streamdown components={MarkdownComponents}>
              {recommendationData.join('')}
            </Streamdown>
          </div>
        </div>
      </div>
      <div className='flex items-center gap-2 px-4 py-3 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-700'>
        <div className='w-2 h-2 bg-blue-400 rounded-full opacity-60'></div>
        <p className='text-sm text-gray-600 dark:text-zinc-400'>
          {t('app.home.aiDisclaimer') ||
            'Recommendations are generated by AI based on your reading history and may not be perfect.'}
        </p>
      </div>
    </div>
  )
}
