name: Fly.io deployment

on:
  push:
    tags:
      - '*'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-arg GIT_COMMIT=${{ github.sha }} -e GIT_COMMIT=${{ github.sha }} -e NODE_ENV=production
