# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.6.x]

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - uses: PromptPal/github-action@v1.0.2
        env:
          PROMPTPAL_ENDPOINT: ${{ secrets.PROMPTPAL_ENDPOINT }}
          PROMPTPAL_API_TOKEN: ${{ secrets.PROMPTPAL_API_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: pp g
      - name: Install dependencies
        run: pnpm install
      - run: pnpm run codegen
      - run: pnpm run build # to make sure this version can be build
        env:
          GIT_COMMIT: ${{ github.sha }}
      - run: pnpm run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.CODEALLS_REPO_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            registry.cn-shanghai.aliyuncs.com/annatarhe/clippingkk-web
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PWD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          GIT_COMMIT: ${{ github.sha }}
          PROMPTPAL_CLIENT_API_TOKEN: ${{ secrets.PROMPTPAL_CLIENT_API_TOKEN }}
        with:
          context: .
          push: true
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            NEXT_PUBLIC_PP_TOKEN=${{ env.PROMPTPAL_CLIENT_API_TOKEN }}
            STANDALONE=1
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
